; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3

; altes Env (für WROOM32)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = yes
upload_port = COM3
lib_deps =
  Adafruit NeoPixel
  ESP32 BLE Arduino
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
board_build.partitions = huge_app.csv


; NEUES Env fürs S3-Board
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = yes
upload_port = COM4
monitor_port = COM4
lib_deps =
  Adafruit NeoPixel
  ESP32 BLE Arduino
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
board_build.partitions = huge_app.csv

; falls du USB-CDC direkt über den S3 nutzen willst:
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
